---
- name: Create AWS resources for the AAP as a Service training events
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

    - name: Create The AWS VPC "ansible-aas-vpc"
      amazon.aws.ec2_vpc_net:
        name: ansible-aas-vpc
        cidr_block: 10.0.0.80/16
        tags:
          Name: ansible-aas-vpc
        tenancy: default
      register: vpc_result

    - name: Create EC2 security group aws-demo-sg
      amazon.aws.ec2_security_group:
        name: aws-demo-sg
        description: Security group for ansible-aas-vpc
        vpc_id: "{{ vpc_result.vpc.id }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 5000
            to_port: 5000
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 50
